const FETCH_POSTAL_LOADING = "FETCH_POSTAL_LOADING";
const FETCH_POSTAL_SUCCESS = "FETCH_POSTAL_SUCCESS";
const FETCH_POSTAL_ERROR = "FETCH_POSTAL_ERROR";
const CLEAR_DATA = "CLEAR_DATA";

export {
	FETCH_POSTAL_LOADING,
	FETCH_POSTAL_SUCCESS,
	FETCH_POSTAL_ERROR,
	CLEAR_DATA,
};
